language: ruby

env:
  global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22
    - KITCHEN_LOCAL_YAML=.kitchen.travis.yml

rvm:
    - 2.1.7

sudo: required
dist: trusty

before_install:
    - sudo usermod -p "`openssl passwd -1 'travis'`" travis

script:
    - pwd
    - cp -v .provisioner.sh bootstrap.sh
    - ln -s /home/travis/build/tempci1216/mk-lab-salt-model /tmp/kitchen
    #- bundle exec rake
    - bundle exec kitchen verify reclass-mk22-scale
    - find .kitchen -name "*.log" | egrep "$(kitchen list |egrep -v Verified$|awk '{print $1}'|xargs |sed 's/\ /|/g')" | xargs -i{} tail -vn 50 {}
    - bundle exec kitchen list

branches:
  only:
    - new_model+ci
