language: ruby

env:
  global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22
    - KITCHEN_LOCAL_YAML=.kitchen.travis.yml

rvm:
    - 2.1.7

sudo: required
dist: trusty

before_install:
    - sudo usermod -p "`openssl passwd -1 'travis'`" travis

script:
    - cp -v .provisioner.sh bootstrap.sh
    #- bundle exec rake
    - bundle exec kitchen verify
    - bundle exec kitchen list

branches:
    only:
        - new_model+ci
