language: ruby

rvm:
#  - 2.1.8
  - 2.2.4
#  - ruby-head

#matrix:
#  allow_failures:
#    - rvm: ruby-head

sudo: true

bundler_args: --without='vagrant'

install:
  # init/start docker in travis
  - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/master/scripts/start_docker.sh)
  # clone & setup ci for test formula
  - bundle install
  #- bundle exec gem install test-kitchen
  #- bundle exec gem install kitchen-docker
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml bundle exec kitchen list

script:
  - export KITCHEN_LOCAL_YAML=.kitchen.travis.yml
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml bundle exec kitchen verify reclass-mk22-scale

after_script:
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml bundle exec kitchen list
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml bundle exec kitchen destroy all
  #- KITCHEN_LOCAL_YAML=.kitchen.travis.yml bundle exec kitchen diagnose --all

after_failure: cat docker_daemon.log

